=== maxperf-de/perfbase/dtd/pb_experiment.dtd
<?xml version="1.0"?>

<!-- ============================================================= -->
<!--                    perfbase experiment specification          -->
<!-- ============================================================= -->


<!--                    Root element                               -->
<!ELEMENT  experiment
                         (name,info,database?,owner?,admin_access?,input_access?,query_access?,parameter+,result+,import?,attachment?)
                                                                     >
<!--                    Experiment meta information                -->
<!ELEMENT  info         (performed_by,project?,synopsis,description) >
<!ELEMENT performed_by (name,organization?)>
<!ELEMENT name         (#PCDATA)>
<!ELEMENT organization (#PCDATA)>
<!ELEMENT project      (#PCDATA)>


<!--                    Perfbase database server                   -->
<!--                    Specify where the PostgreSQL database
                        server which will store this experiment is
                        located. This information can also be
                        passed via the commandline or envrironment
                        variables. If nohting is specified
                        anwhere, default settings do apply (server
                        runnning on 'localhost' with default port
                        numbers and no passwords or other access
                        right limitations.                         -->
<!ELEMENT  database     (host?,port?,user?,passwd?)                  >
<!--                    Access rigths to experiment database       -->
<!--                    The access rights to an experiment
                        database can be controled on three levels,
                        which are the right to query data from the
                        database, to insert data into the database
                        and to administrate the database. All
                        these level can be assigned to an arbitrary
                        list of users and groups. All admin's have input
                        and query rights, and all input users also have 
                        query rights. 
                        Please note that these are PostgreSQL users and 
                        groups, not system users and groups! Also, these
                        users and groups need to exist and need to have the
                        basic general rights for the database.      -->
<!ELEMENT  admin_access   (group|user)+                                >
<!ELEMENT  input_access   (group|user)+                                >
<!ELEMENT  query_access   (group|user)+                                >
<!--                    Each database has exactly one owner. By default,
                        it is the user who creates the database. To chose
                        a different owner, enter his database user id here.
                        Note that the owner is the only one who can delete
                        a database, and that the owner can not be changed
                        afterwards.                                  -->
<!ELEMENT  owner       (#PCDATA)                                       >

<!ELEMENT host         (#PCDATA)>
<!ELEMENT port         (#PCDATA)>
<!ELEMENT passwd       (#PCDATA)>
<!ELEMENT group        (#PCDATA)>
<!ELEMENT user         (#PCDATA)>

<!ELEMENT parameter    (name,synopsis?,description?,datatype,unit?,valid*,default?)>
<!ATTLIST parameter     is_numeric  (yes|no) "no"
                        occurrence  (once|multiple) "multiple">
<!ELEMENT result       (name,synopsis?,description?,datatype,unit?,default?)>
<!ATTLIST result        is_numeric  (yes|no) "no"
                        occurrence  (once|multiple) "multiple">

<!ELEMENT unit         (fraction|product|(base_unit,scaling?))>
<!ELEMENT fraction     (dividend,divisor)>
<!ELEMENT dividend     (fraction|product|(base_unit,scaling?))>
<!ELEMENT divisor      (fraction|product|(base_unit,scaling?))>
<!ELEMENT product      (factor+)>
<!ELEMENT factor       (fraction|product|(base_unit,scaling?))>

<!-- Valid 'datatype's are integer,float,string,text,date,timeofday,duration,timestamp,binary,boolean,version -->
<!ELEMENT datatype     (#PCDATA)>
<!-- size attribute for integer and float datatype -->
<!ATTLIST datatype     size  (2|4|8)  "4">
<!-- Valid 'base_unit's are are: none,%,byte,bit,flop,op,process,event,s,Hz,m,g,A,K,mol,cd,Y,$,EUR -->
<!ELEMENT base_unit    (#PCDATA)>
<!-- Valid 'scaling' factors are Kilo,Mega,Giga,Tera,Peta,milli,micro,nano,pico,femto,Ki,Mi,Gi,Ti,Pi -->
<!ELEMENT scaling      (#PCDATA)>

<!ELEMENT valid        (#PCDATA)>
<!-- Default content for a parameter or result value can be specified. This content will 
     be retrieved from a run of an experiment in which no content was set from the input files
     (for this value). If no <default> element is specified for a value, then an empty ('NULL')
     content is *not* allowed for this value! To allow 'NULL' content, provide an empty <default>
     element. If a query checks a value in a run for a specific content, than this check will
     always return "does not match" for NULL content! -->
<!ELEMENT default      (#PCDATA)>

<!ELEMENT synopsis     (#PCDATA)>
<!ELEMENT description  (#PCDATA)>

<!ELEMENT import       (#PCDATA)>
<!ELEMENT attachment   (#PCDATA)>

=== maxperf-de/perfbase/test/derived/derived_exp_3.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>derived_TEST</name>
  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase test suite</project>
    <synopsis>Test derived parameters in an input description.</synopsis>
    <description> Check definitions of derived parameters inside an input description.
       </description>
  </info>

  <parameter occurrence="once">
    <name>N_nodes</name>
    <synopsis>number of nodes</synopsis>

    <datatype>integer</datatype>
  </parameter>

  <parameter occurrence="once">
    <name>N_cpn</name>
    <synopsis>number of cpus per node</synopsis>

    <datatype>integer</datatype>
  </parameter>

  <parameter occurrence="once">
    <name>N_cpus</name>
    <synopsis>number of cpus</synopsis>

    <datatype>integer</datatype>
  </parameter>

  <parameter>
    <name>N_ppn</name>
    <synopsis>number of processs per node</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>process</base_unit>
    </unit>
  </parameter>

  <parameter>
    <name>N_procs</name>
    <synopsis>number of processes</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>process</base_unit>
    </unit>
  </parameter>

  <result>
    <name>T</name>
    <synopsis>total time to solution</synopsis>

    <datatype>duration</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>

</experiment>

=== maxperf-de/perfbase/test/distrib/distrib_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>distrib_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for bin operator and related plotting functionality.</synopsis>
    <description>
      This test will show distribution information.
    </description>
  </info>

  <parameter>
    <name>S_msg</name>
    <synopsis>message size</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
  </parameter>

  <result>
    <name>l_msg</name>
    <synopsis>message latency</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>

</experiment>

=== maxperf-de/perfbase/test/multi_target/multi_target_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>multi_target_TEST</name>
  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase test suite</project>
    <synopsis>Test processing of query object which have multiple targets.</synopsis>
    <description> A single object within a query may be referenced by more than one dependent objects
      which will work on its data. To optimize query performance, the data should only be stored once.
    </description>
  </info>
  
  <parameter>
    <name>S_msg</name>
    <synopsis>message size</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
  </parameter>
  
  <parameter>
    <name>MPI_version</name>
    
    <!-- datatype 'version' would be better, but requries libvnbr to be installed. -->
    <datatype>string</datatype>
    <synopsis>Version of the MPI library</synopsis>
  </parameter>
    
  <result>
    <name>T_pp</name>
    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
    <synopsis>message latency</synopsis>
  </result>
  
</experiment>

=== maxperf-de/perfbase/examples/mpiproginf/mpiproginf_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>MPIPROGINF_DEMO</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>SX Performance Analysis</project>
    <synopsis>Analyse application performance using the information that 'mpirun' provides.</synopsis>
    <description>
      'mpirun' of NEC MPI/SX does provide the option to dump per-process information
      on consumed time, integer and floating point operation rates, vectorization rate,
      memory access delays etc. that can be used to judge the efficiency of a (parallel)
      vectorized application.
    </description>
  </info>
  
  <parameter occurrence="once">
    <name>N_proc</name>
    <synopsis>number of processes</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>process</base_unit>
    </unit>
  </parameter>

  <parameter>
    <name>rank</name>
    <synopsis>process rank</synopsis>

    <datatype>integer</datatype>
  </parameter>

  <parameter occurrence="once">
    <name>app</name>
    <synopsis>application name</synopsis>

    <datatype>string</datatype>
  </parameter>

  <parameter occurrence="once">
    <name>version</name>
    <synopsis>application version</synopsis>

    <datatype>string</datatype>
    <default></default>
  </parameter>

  <parameter occurrence="once">
    <name>flags</name>
    <synopsis>compiler flags</synopsis>

    <datatype>string</datatype>
    <default></default>
  </parameter>

  <result>
    <name>T_real</name>
    <synopsis>real time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>

  <result>
    <name>T_user</name>
    <synopsis>user time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>

  <result>
    <name>T_sys</name>
    <synopsis>system time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>

  <result>
    <name>T_vec</name>
    <synopsis>vector time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>

  <result>
    <name>N_i</name>
    <synopsis>instruction count</synopsis>

    <datatype size="8">integer</datatype>
  </result>

  <result>
    <name>N_ivec</name>
    <synopsis>vector instruction count</synopsis>

    <datatype size="8">integer</datatype>
  </result>

  <result>
    <name>N_vece</name>
    <synopsis>vector element count</synopsis>

    <datatype size="8">integer</datatype>
  </result>

  <result>
    <name>N_iflop</name>
    <synopsis>floating point instruction count</synopsis>

    <datatype size="8">integer</datatype>
  </result>

  <result>
    <name>MOPS</name>
    <synopsis>integer instruction rate</synopsis>

    <datatype>integer</datatype>
    <unit>
      <fraction>
	<dividend>
	  <base_unit>op</base_unit>
	  <scaling>Mega</scaling>
	</dividend>
	<divisor>
	  <base_unit>s</base_unit>
	</divisor>
      </fraction>
    </unit>
  </result>

  <result>
    <name>MFLOPS</name>
    <synopsis>floating point instruction rate</synopsis>

    <datatype>integer</datatype>
    <unit>
      <fraction>
	<dividend>
	  <base_unit>flop</base_unit>
	  <scaling>Mega</scaling>
	</dividend>
	<divisor>
	  <base_unit>s</base_unit>
	</divisor>
      </fraction>
    </unit>
  </result>
  
  <result>
    <name>l_vec</name>
    <synopsis>average vector length</synopsis>

    <datatype>float</datatype>
  </result>

  <result>
    <name>r_vec</name>
    <synopsis>vector operation ratio</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>%</base_unit>
    </unit>
  </result>

  <result>
    <name>S_mem</name>
    <synopsis>memory used</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>byte</base_unit>
      <scaling>Mega</scaling>
    </unit>
  </result>

  <result>
    <name>S_gmem</name>
    <synopsis>global memory used</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>byte</base_unit>
      <scaling>Mega</scaling>
    </unit>
  </result>

  <result>
    <name>T_imiss</name>
    <synopsis>instruction cache miss time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>

  <result>
    <name>T_opmiss</name>
    <synopsis>operand cache miss time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>

  <result>
    <name>T_bank</name>
    <synopsis>bank conflict time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>

</experiment>

=== maxperf-de/perfbase/test/sweep/sweep_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>sweep_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for correct handling of parameter sweeps</synopsis>
    <description>
          Automatically query a range of parameters with a simplified syntax.
       </description>
  </info>

  <parameter occurrence="once">
    <name>MPI_version</name>
    <synopsis>MPI library version</synopsis>

    <!-- datatype 'version' would be better, but requries libvnbr to be installed. -->
    <datatype>string</datatype>
  </parameter>

  <parameter occurrence="once">
    <name>I</name>
    <synopsis>Interconnect</synopsis>

    <datatype>string</datatype>
    <valid>SCI</valid>
    <valid>Myrinet</valid>
  </parameter>

  <parameter>
    <name>S_msg</name>
    <synopsis>message size</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
  </parameter>

  <result>
    <name>T_pp</name>
    <synopsis>halve of roundtrip latency</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
  </result>
</experiment>

=== maxperf-de/perfbase/test/default/default_exp_float_4.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>default_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for correct handling of default values.</synopsis>
    <description>
      This test checks if default values are properly set (or proper error messages are
      generated) if no content for a value could be found.
    </description>
  </info>

  <parameter occurrence="once">
    <name>type</name>
    <synopsis>vehicle type</synopsis>

    <datatype>string</datatype>
  </parameter>

  <result occurrence="once">
    <name>v</name>
    <synopsis>vehicle speed</synopsis>

    <datatype>float</datatype>
    <default>11.1</default>
  </result>

  <parameter>
    <name>rpm</name>
    <synopsis>revolutions per minute</synopsis>

    <datatype>integer</datatype>
    <default></default>
  </parameter>

  <result>
    <name>CO_2</name>
    <synopsis>emissions</synopsis>

    <datatype>float</datatype>
    <default></default>
  </result>

</experiment>

=== maxperf-de/perfbase/test/combiner2/combiner2_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>combiner2_TEST</name>
  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase test suite</project>
    <synopsis>Test combiner element to handle sweeps.</synopsis>
    <description> 
      Combine data from parameter sweeps in different ways.
    </description>
  </info>
      
  <parameter occurrence="once">
    <name>V_net</name>
    <synopsis>network speed</synopsis>
    
    <datatype>float</datatype>
    <unit>
      <fraction>
	<dividend>
	  <base_unit>bit</base_unit>
	  <scaling>Mega</scaling>
	</dividend>
	<divisor>
	  <base_unit>s</base_unit>
	</divisor>
      </fraction>
    </unit>
  </parameter>
  
  <parameter occurrence="once">
    <name>API</name>
    <synopsis>API type</synopsis>

    <datatype>string</datatype>
  </parameter>

  <parameter>
    <name>S_msg</name>
    <synopsis>message size</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
  </parameter>

  <result>
    <name>T_pp</name>
    <synopsis>message latency</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>
  
</experiment>

=== maxperf-de/perfbase/examples/PMB/pmb_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>PMB_DEMO</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>Optimization of MPI Collective Operations</project>
    <synopsis>Results of Pallas MPI Benchmark</synopsis>
    <description>
         We want to track the performance changes that we achieve with
         new algorithms and parameter optimization for collective operations.
       </description>
  </info>

  <parameter>
    <name>S_chunk</name>
    <synopsis>amount of data (per process)</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
  </parameter>

  <parameter>
    <name>N_proc</name>
    <synopsis>number of processes</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>process</base_unit>
    </unit>
  </parameter>

  <parameter occurrence="once">
    <name>MPI_version</name>
    <synopsis>Version of the MPI library</synopsis>

    <default>1.3</default>
    <!-- 'version' would be the better datatype here, but requires a custom    -->
    <!-- SQL datatype to be installed. We don't want this to be a show-stopper.-->
    <datatype>string</datatype>
  </parameter>

  <parameter occurrence="once">
    <name>machine</name>
    <synopsis>platform on which the test was performed</synopsis>

    <datatype>string</datatype>
    <valid>SX-5</valid>
    <valid>SX-6</valid>
    <valid>SX-7</valid>
    <valid>SX-8</valid>
    <valid>TX-7</valid>
    <valid>IA-32 Cluster</valid>
    <valid>IA-64 Cluster</valid>
    <default>IA-32 Cluster</default>
  </parameter>

  <parameter occurrence="once">
    <name>interconnect</name>
    <synopsis>intra-node interconnect</synopsis>

    <datatype>string</datatype>
    <valid>IXS</valid>
    <valid>Myrinet</valid>
    <valid>Quadrics Elan3</valid>
    <valid>Quadrics Elan4</valid>
    <valid>Infiniband</valid>
    <valid>SCI</valid>
    <valid>Gigabit Ethernet</valid>
    <default>SCI</default>
  </parameter>

  <parameter>
    <name>operation</name>
    <synopsis>PMB operation that was measured</synopsis>

    <datatype>string</datatype>
  </parameter>

  <result>
    <name>T_min</name>
    <synopsis>minimal time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
    <default>-1.0</default>
  </result>

  <result>
    <name>T_max</name>
    <synopsis>maximum time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
    <default>-1.0</default>
  </result>

  <result>
    <name>T_avg</name>
    <synopsis>average time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
    <default>-1.0</default>
  </result>

  <result>
    <name>B</name>
    <synopsis>average bandwidth</synopsis>

    <datatype>float</datatype>
    <unit>
      <fraction>
	<dividend>
	  <base_unit>byte</base_unit>
	  <scaling>Mega</scaling>
	</dividend>
	<divisor><base_unit>s</base_unit></divisor>
      </fraction>
    </unit>
    <default>-1.0</default>
  </result>

</experiment>
