=== maxperf-de/perfbase/dtd/pb_experiment.dtd
<?xml version="1.0"?>

<!-- ============================================================= -->
<!--                    perfbase experiment specification          -->
<!-- ============================================================= -->


<!--                    Root element                               -->
<!ELEMENT  experiment
                         (name,info,database?,owner?,admin_access?,input_access?,query_access?,parameter+,result+,import?,attachment?)
                                                                     >
<!--                    Experiment meta information                -->
<!ELEMENT  info         (performed_by,project?,synopsis,description) >
<!ELEMENT performed_by (name,organization?)>
<!ELEMENT name         (#PCDATA)>
<!ELEMENT organization (#PCDATA)>
<!ELEMENT project      (#PCDATA)>


<!--                    Perfbase database server                   -->
<!--                    Specify where the PostgreSQL database
                        server which will store this experiment is
                        located. This information can also be
                        passed via the commandline or envrironment
                        variables. If nohting is specified
                        anwhere, default settings do apply (server
                        runnning on 'localhost' with default port
                        numbers and no passwords or other access
                        right limitations.                         -->
<!ELEMENT  database     (host?,port?,user?,passwd?)                  >
<!--                    Access rigths to experiment database       -->
<!--                    The access rights to an experiment
                        database can be controled on three levels,
                        which are the right to query data from the
                        database, to insert data into the database
                        and to administrate the database. All
                        these level can be assigned to an arbitrary
                        list of users and groups. All admin's have input
                        and query rights, and all input users also have 
                        query rights. 
                        Please note that these are PostgreSQL users and 
                        groups, not system users and groups! Also, these
                        users and groups need to exist and need to have the
                        basic general rights for the database.      -->
<!ELEMENT  admin_access   (group|user)+                                >
<!ELEMENT  input_access   (group|user)+                                >
<!ELEMENT  query_access   (group|user)+                                >
<!--                    Each database has exactly one owner. By default,
                        it is the user who creates the database. To chose
                        a different owner, enter his database user id here.
                        Note that the owner is the only one who can delete
                        a database, and that the owner can not be changed
                        afterwards.                                  -->
<!ELEMENT  owner       (#PCDATA)                                       >

<!ELEMENT host         (#PCDATA)>
<!ELEMENT port         (#PCDATA)>
<!ELEMENT passwd       (#PCDATA)>
<!ELEMENT group        (#PCDATA)>
<!ELEMENT user         (#PCDATA)>

<!ELEMENT parameter    (name,synopsis?,description?,datatype,unit?,valid*,default?)>
<!ATTLIST parameter     is_numeric  (yes|no) "no"
                        occurrence  (once|multiple) "multiple">
<!ELEMENT result       (name,synopsis?,description?,datatype,unit?,default?)>
<!ATTLIST result        is_numeric  (yes|no) "no"
                        occurrence  (once|multiple) "multiple">

<!ELEMENT unit         (fraction|product|(base_unit,scaling?))>
<!ELEMENT fraction     (dividend,divisor)>
<!ELEMENT dividend     (fraction|product|(base_unit,scaling?))>
<!ELEMENT divisor      (fraction|product|(base_unit,scaling?))>
<!ELEMENT product      (factor+)>
<!ELEMENT factor       (fraction|product|(base_unit,scaling?))>

<!-- Valid 'datatype's are integer,float,string,text,date,timeofday,duration,timestamp,binary,boolean,version -->
<!ELEMENT datatype     (#PCDATA)>
<!-- size attribute for integer and float datatype -->
<!ATTLIST datatype     size  (2|4|8)  "4">
<!-- Valid 'base_unit's are are: none,%,byte,bit,flop,op,process,event,s,Hz,m,g,A,K,mol,cd,Y,$,EUR -->
<!ELEMENT base_unit    (#PCDATA)>
<!-- Valid 'scaling' factors are Kilo,Mega,Giga,Tera,Peta,milli,micro,nano,pico,femto,Ki,Mi,Gi,Ti,Pi -->
<!ELEMENT scaling      (#PCDATA)>

<!ELEMENT valid        (#PCDATA)>
<!-- Default content for a parameter or result value can be specified. This content will 
     be retrieved from a run of an experiment in which no content was set from the input files
     (for this value). If no <default> element is specified for a value, then an empty ('NULL')
     content is *not* allowed for this value! To allow 'NULL' content, provide an empty <default>
     element. If a query checks a value in a run for a specific content, than this check will
     always return "does not match" for NULL content! -->
<!ELEMENT default      (#PCDATA)>

<!ELEMENT synopsis     (#PCDATA)>
<!ELEMENT description  (#PCDATA)>

<!ELEMENT import       (#PCDATA)>
<!ELEMENT attachment   (#PCDATA)>

=== maxperf-de/perfbase/test/limit/limit_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>limit_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for correct functionality of operator 'limit'.</synopsis>
    <description>
      This test lets operators work on a single data vector from a single source.
    </description>
  </info>

  <parameter>
    <name>p</name>
    <synopsis>the parameter</synopsis>

    <datatype>float</datatype>
  </parameter>

  <result>
    <name>r1</name>
    <synopsis>the first result</synopsis>

    <datatype>float</datatype>
  </result>

  <result>
    <name>r2</name>
    <synopsis>the second result</synopsis>

    <datatype>float</datatype>
  </result>

</experiment>

=== maxperf-de/perfbase/test/frequency/frequency_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>frequency_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>IAT GmbH</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for frequency operator</synopsis>
    <description>
          Some basic tests for the frequency operator
    </description>
  </info>

  <parameter occurrence="once">
    <name>r</name>
    <synopsis>run</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>none</base_unit>
    </unit>
  </parameter>

  <parameter>
    <name>t</name>
    <synopsis>time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </parameter>

  <result>
    <name>v</name>
    <synopsis>value</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>none</base_unit>
    </unit>
  </result>

</experiment>

=== maxperf-de/perfbase/test/fixed/fixed_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>fixed_TEST</name>
  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase test suite</project>
    <synopsis>Test fixed values in a query.</synopsis>
    <description> Control definitions inside a query via "constants" (fixed values), defined
         either within the query or on the command line.
       </description>
  </info>

  <parameter>
    <name>S_msg</name>
    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
    <synopsis>message size</synopsis>
  </parameter>

    <parameter>
      <name>MPI_version</name>

      <!-- datatype 'version' would be better, but requries libvnbr to be installed. -->
      <datatype>string</datatype>
      <synopsis>Version of the MPI library</synopsis>
    </parameter>

    <result>
      <name>T_pp</name>
      <datatype>float</datatype>
      <unit>
	<base_unit>s</base_unit>
      </unit>
      <synopsis>message latency</synopsis>
    </result>

</experiment>

=== maxperf-de/perfbase/test/pset/pset_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>pset_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for correct usage of parameter sets</synopsis>
    <description>
      Create different parameter sets, then import some data files, and
      finally run a query to see if the result is correct.
    </description>
  </info>

  <parameter occurrence="once">
    <name>P_1</name>
    <synopsis>parameter one</synopsis>

    <datatype>float</datatype>
  </parameter>

  <parameter occurrence="once">
    <name>P_2</name>
    <synopsis>parameter two</synopsis>

    <datatype>string</datatype>
  </parameter>

  <parameter>
    <name>p</name>
    <synopsis>running parameter</synopsis>

    <datatype>integer</datatype>
  </parameter>

  <result>
    <name>r</name>
    <synopsis>running result</synopsis>

    <datatype>float</datatype>
  </result>

</experiment>

=== maxperf-de/perfbase/test/slice/slice_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>slice_TEST</name>
  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase test suite</project>
    <synopsis>Test slice operator.</synopsis>
    <description> 
      Import a number of runs with the run-order different from the order of the "performed"
      timestamps. Apply various slice operations and validate the results.
    </description>
  </info>

  <parameter>
    <name>S_msg</name>
    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
    <synopsis>message size</synopsis>
  </parameter>

  <result>
    <name>T_pp</name>
    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
    <synopsis>message latency</synopsis>
  </result>
  
</experiment>

=== maxperf-de/perfbase/test/update/update_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>update_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase test suite</project>
    <synopsis>Message latency for ping-pong style communication between two processes</synopsis>
    <description>
      This is a very basic experiment as it only defines a message size and a related latency.
      It could become useful by adding parameters like interconnect, API, software version etc.
    </description>
  </info>

  <parameter>
    <name>S_msg</name>
    <synopsis>message size</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
  </parameter>

  <parameter occurrence="once">
    <name>MPI_version</name>
    <synopsis>MPI library version</synopsis>

    <!-- datatype 'version' would be better, but requries libvnbr to be installed. -->
    <datatype>string</datatype>
  </parameter>

  <result>
    <name>T_pp</name>
    <synopsis>message latency (halve roundtrip time)</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
  </result>
</experiment>

=== maxperf-de/perfbase/test/boolean/boolean_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>boolean_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for parsing boolean values</synopsis>
    <description>
      Determine the state of a boolean variable via various means.
    </description>
  </info>

  <parameter occurrence="once">
    <name>N_proc</name>
    <synopsis>number of processes</synopsis>

    <datatype>integer</datatype>    
    <unit>
      <base_unit>process</base_unit>
    </unit>
  </parameter>

  <parameter occurrence="once">
    <name>IXS</name>
    <datatype>boolean</datatype>
  </parameter>
  
  <result>
    <name>l</name>
    <synopsis>latency</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
  </result>

</experiment>

=== maxperf-de/perfbase/test/barchart/barchart_exp_desc.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>barchart_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for correct creation of barcharts</synopsis>
    <description>
          Because of the artifical creation of x-index values for the data sets to 
          be plotted, correctnes of barcharts is sensitive to non-matching "x-data"
          when muliple data sets are to be plotted into a single chart. This experiment
          tests the behaviour of perfbase for these cases.
       </description>
  </info>

  <parameter occurrence="once">
    <name>MPI_version</name>
    <synopsis>Version of the MPI library</synopsis>

    <datatype>version</datatype>
  </parameter>

  <parameter>
    <name>S_msg</name>
    <synopsis>message size</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
  </parameter>

  <result>
    <name>T_pp</name>
    <synopsis>halve of roundtrip latency</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
  </result>
</experiment>
