=== maxperf-de/perfbase/dtd/pb_experiment.dtd
<?xml version="1.0"?>

<!-- ============================================================= -->
<!--                    perfbase experiment specification          -->
<!-- ============================================================= -->


<!--                    Root element                               -->
<!ELEMENT  experiment
                         (name,info,database?,owner?,admin_access?,input_access?,query_access?,parameter+,result+,import?,attachment?)
                                                                     >
<!--                    Experiment meta information                -->
<!ELEMENT  info         (performed_by,project?,synopsis,description) >
<!ELEMENT performed_by (name,organization?)>
<!ELEMENT name         (#PCDATA)>
<!ELEMENT organization (#PCDATA)>
<!ELEMENT project      (#PCDATA)>


<!--                    Perfbase database server                   -->
<!--                    Specify where the PostgreSQL database
                        server which will store this experiment is
                        located. This information can also be
                        passed via the commandline or envrironment
                        variables. If nohting is specified
                        anwhere, default settings do apply (server
                        runnning on 'localhost' with default port
                        numbers and no passwords or other access
                        right limitations.                         -->
<!ELEMENT  database     (host?,port?,user?,passwd?)                  >
<!--                    Access rigths to experiment database       -->
<!--                    The access rights to an experiment
                        database can be controled on three levels,
                        which are the right to query data from the
                        database, to insert data into the database
                        and to administrate the database. All
                        these level can be assigned to an arbitrary
                        list of users and groups. All admin's have input
                        and query rights, and all input users also have 
                        query rights. 
                        Please note that these are PostgreSQL users and 
                        groups, not system users and groups! Also, these
                        users and groups need to exist and need to have the
                        basic general rights for the database.      -->
<!ELEMENT  admin_access   (group|user)+                                >
<!ELEMENT  input_access   (group|user)+                                >
<!ELEMENT  query_access   (group|user)+                                >
<!--                    Each database has exactly one owner. By default,
                        it is the user who creates the database. To chose
                        a different owner, enter his database user id here.
                        Note that the owner is the only one who can delete
                        a database, and that the owner can not be changed
                        afterwards.                                  -->
<!ELEMENT  owner       (#PCDATA)                                       >

<!ELEMENT host         (#PCDATA)>
<!ELEMENT port         (#PCDATA)>
<!ELEMENT passwd       (#PCDATA)>
<!ELEMENT group        (#PCDATA)>
<!ELEMENT user         (#PCDATA)>

<!ELEMENT parameter    (name,synopsis?,description?,datatype,unit?,valid*,default?)>
<!ATTLIST parameter     is_numeric  (yes|no) "no"
                        occurrence  (once|multiple) "multiple">
<!ELEMENT result       (name,synopsis?,description?,datatype,unit?,default?)>
<!ATTLIST result        is_numeric  (yes|no) "no"
                        occurrence  (once|multiple) "multiple">

<!ELEMENT unit         (fraction|product|(base_unit,scaling?))>
<!ELEMENT fraction     (dividend,divisor)>
<!ELEMENT dividend     (fraction|product|(base_unit,scaling?))>
<!ELEMENT divisor      (fraction|product|(base_unit,scaling?))>
<!ELEMENT product      (factor+)>
<!ELEMENT factor       (fraction|product|(base_unit,scaling?))>

<!-- Valid 'datatype's are integer,float,string,text,date,timeofday,duration,timestamp,binary,boolean,version -->
<!ELEMENT datatype     (#PCDATA)>
<!-- size attribute for integer and float datatype -->
<!ATTLIST datatype     size  (2|4|8)  "4">
<!-- Valid 'base_unit's are are: none,%,byte,bit,flop,op,process,event,s,Hz,m,g,A,K,mol,cd,Y,$,EUR -->
<!ELEMENT base_unit    (#PCDATA)>
<!-- Valid 'scaling' factors are Kilo,Mega,Giga,Tera,Peta,milli,micro,nano,pico,femto,Ki,Mi,Gi,Ti,Pi -->
<!ELEMENT scaling      (#PCDATA)>

<!ELEMENT valid        (#PCDATA)>
<!-- Default content for a parameter or result value can be specified. This content will 
     be retrieved from a run of an experiment in which no content was set from the input files
     (for this value). If no <default> element is specified for a value, then an empty ('NULL')
     content is *not* allowed for this value! To allow 'NULL' content, provide an empty <default>
     element. If a query checks a value in a run for a specific content, than this check will
     always return "does not match" for NULL content! -->
<!ELEMENT default      (#PCDATA)>

<!ELEMENT synopsis     (#PCDATA)>
<!ELEMENT description  (#PCDATA)>

<!ELEMENT import       (#PCDATA)>
<!ELEMENT attachment   (#PCDATA)>

=== maxperf-de/perfbase/test/multi/multi_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>multi_TEST</name>
  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase</project>
    <synopsis>Regression test for multiple input files.</synopsis>
    <description>
          Test case for processing multiple input files: data for a single run
          can be gathered from an arbitrary number of files.
       </description>
  </info>

  <parameter>
    <name>S_msg</name>
    <synopsis>Size of message in bytes</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
  </parameter>

  <parameter>
    <name>CPU_load</name>
    <synopsis>Load of the CPU when processing this message transmission</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>%</base_unit>
    </unit>
  </parameter>

  <result>
    <name>T_pp</name>
    <synopsis>Ping-pong message latency (halve of roundtrip time)</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>

</experiment>

=== maxperf-de/perfbase/test/map/map_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>map_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for mapping of data</synopsis>
    <description>
      Map data that was retrieved via filename, named or explicit location, or table.
    </description>
  </info>

  <parameter>
    <name>fs</name>
    <synopsis>filesystem</synopsis>

    <datatype>string</datatype>
    <valid>UFS</valid>
    <valid>SFS</valid>
    <valid>NFS</valid>
    <valid>XFS</valid>
  </parameter>

  <result>
    <name>T</name>
    <synopsis>time to start</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>

</experiment>

=== maxperf-de/perfbase/test/opendoc/opendoc_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>opendoc_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>IAT GmbH, Germany</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for creation of OpenDoc spreadsheets</synopsis>
    <description>
           Automatically create useful, multicolumn tables, especially 
           in combination with parameter sweeps.
    </description>
  </info>

  <parameter occurrence="once">
    <name>MPI_version</name>
    <synopsis>MPI library version</synopsis>

    <!-- datatype 'version' would be better, but requries libvnbr to be installed. -->
    <datatype>string</datatype>
  </parameter>

  <parameter occurrence="once">
    <name>I</name>
    <synopsis>Interconnect</synopsis>

    <datatype>string</datatype>
    <valid>SCI</valid>
    <valid>Myrinet</valid>
  </parameter>

  <parameter>
    <name>S_msg</name>
    <synopsis>message size</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
  </parameter>

  <result>
    <name>T_pp</name>
    <synopsis>halve of roundtrip latency</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
  </result>

  <result>
    <name>T_gap</name>
    <synopsis>send gap</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
  </result>
</experiment>

=== maxperf-de/perfbase/test/missing/missing_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>missing_TEST</name>
  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase test suite</project>
    <synopsis>Test behaviour for missing values in a query.</synopsis>
    <description> 
      perfbase supports different actions that are to be perfomed if a content
      for a value is not found in the input files.
    </description>
  </info>
  
  <parameter>
    <name>S_msg</name>
    <synopsis>message size</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
  </parameter>
  
  <parameter occurrence="once">
    <name>MPI_version</name>
    <synopsis>Version of the MPI library</synopsis>

    <!-- datatype 'version' would be better, but requries libvnbr to be installed. -->
    <datatype>string</datatype>
  </parameter>

  <parameter occurrence="once">
    <name>OS_version</name>
    <synopsis>Version of the OS</synopsis>

    <!-- datatype 'version' would be better, but requries libvnbr to be installed. -->
    <datatype>string</datatype>
    <default>1.0</default>
  </parameter>

  <result>
    <name>T_pp</name>
    <synopsis>message latency</synopsis>
    
    <datatype>float</datatype>
    <unit>
	<base_unit>s</base_unit>
    </unit>
    <default></default>
  </result>

</experiment>

=== maxperf-de/perfbase/examples/auto_compare/PMB/auto-pmb_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>PMB_auto_DEMO</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>Optimization of MPI Collective Operations</project>
    <synopsis>Results of Intel/Pallas MPI Benchmark</synopsis>
    <description>
         We want to track the performance changes that we achieve with
         new algorithms and parameter optimization for collective operations.
    </description>
  </info>

  <parameter>
    <name>S_chunk</name>
    <synopsis>amount of data (per process)</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
  </parameter>

  <parameter>
    <name>N_proc</name>
    <synopsis>number of processes</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>process</base_unit>
    </unit>
  </parameter>

  <parameter occurence="once">
    <name>N_ppn</name>
    <synopsis>number of processes per node</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>process</base_unit>
    </unit>
  </parameter>

  <parameter occurrence="once">
    <name>N_node</name>
    <synopsis>number of nodes</synopsis>

    <datatype>integer</datatype>
    <default></default>
  </parameter>

  <parameter occurence="once">
    <name>MPI_vendor</name>
    <synopsis>Vendor of the MPI library</synopsis>

    <datatype>string</datatype>
    <valid>A</valid>
    <valid>B</valid>
    <valid>C</valid>
  </parameter>

  <parameter>
    <name>operation</name>
    <synopsis>MPI operation</synopsis>

    <datatype>string</datatype>
  </parameter>

  <result>
    <name>T_min</name>
    <synopsis>minimal time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
    <default></default>
  </result>

  <result>
    <name>T_max</name>
    <synopsis>maximum time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
    <default></default>
  </result>

  <result>
    <name>T_avg</name>
    <synopsis>average time</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
    <default></default>
  </result>

  <result>
    <name>B</name>
    <synopsis>average bandwidth</synopsis>

    <datatype>float</datatype>
    <unit>
      <fraction>
	<dividend>
	  <base_unit>byte</base_unit>
	  <scaling>Mega</scaling>
	</dividend>
	<divisor><base_unit>s</base_unit></divisor>
      </fraction>
    </unit>
    <default></default>
  </result>

</experiment>

=== maxperf-de/perfbase/test/regexp/regexp_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>regexp_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for parsing with regular expressions</synopsis>
    <description>
      Test different types of locations with regular expressions
    </description>
  </info>

  <parameter occurrence="once">
    <name>N_proc</name>
    <synopsis>number of processes</synopsis>

    <datatype>integer</datatype>    
    <unit>
      <base_unit>process</base_unit>
    </unit>
  </parameter>
 
  <result>
    <name>l</name>
    <synopsis>latency</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
      <scaling>micro</scaling>
    </unit>
  </result>

</experiment>

=== maxperf-de/perfbase/test/sweep_group/sweep_group_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>sweep_group_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for "good" plotting of sweeps over multiple parameters</synopsis>
    <description>
      Output is sometimes of "undesired" format using multiple sweeps. This test is used to 
      improve on this. Inspired by a SPEC-experiment of James Cownie, Intel.
    </description>
  </info>

  <parameter occurrence="once">
    <name>bench</name>
    <synopsis>benchmark name</synopsis>

    <datatype>string</datatype>
    <valid>crunch</valid>
    <valid>seek</valid>
    <valid>swim</valid>
  </parameter>

  <parameter>
    <name>N_threads</name>
    <synopsis>number of threads</synopsis>

    <datatype>integer</datatype>
  </parameter>

  <result>
    <name>T</name>
    <synopsis>execution time</synopsis>
    <description>Execution time measured as wall clock time.</description>

    <datatype>float</datatype>
    <unit>
      <base_unit>s</base_unit>
    </unit>
  </result>
</experiment>

=== maxperf-de/perfbase/test/order/order_exp.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment SYSTEM "../../dtd/pb_experiment.dtd">

<experiment>
  <name>order_TEST</name>

  <info>
    <performed_by> 
      <name>Joachim Worringen</name>
      <organization>Computer and Communications Research Lab, NEC Europe Ltd.</organization>
    </performed_by> 
    <project>perfbase testsuite</project>
    <synopsis>Test for correct handling of non-sorted input data.</synopsis>
    <description>
      This test imports data which is not sorted by it's parameter value. This data
      is then processed differently (no sorting, ascending, descending)
    </description>
  </info>

  <parameter>
    <name>p</name>
    <synopsis>the running parameter</synopsis>

    <datatype>float</datatype>
  </parameter>

  <parameter occurrence="once">
    <name>T</name>
    <synopsis>the constant parameter</synopsis>

    <datatype>integer</datatype>    
  </parameter>

  <result>
    <name>r</name>
    <synopsis>the result value</synopsis>

    <datatype>float</datatype>
  </result>

</experiment>
