=== maxperf-de/perfbase/dtd/pb_experiment_update.dtd
<?xml version="1.0"?>

<!ELEMENT experiment_update (experiment,info?,database?,access_add?,access_change?,access_revoke?,parameter*,result*,import?,attachment?)>


<!ELEMENT info         (performed_by?,project?,synopsis?,description?)>
<!ELEMENT performed_by (name?,organization?)>
<!ELEMENT database     (host?,port?,user?,passwd?)>

<!ELEMENT access_add      (admin_access?,input_access?,query_access?) >
<!ELEMENT access_change   (admin_access?,input_access?,query_access?) >
<!ELEMENT access_revoke   (group|user)+                               >

<!ELEMENT admin_access   (group|user)+                                >
<!ELEMENT input_access   (group|user)+                                >
<!ELEMENT query_access   (group|user)+                                >

<!ELEMENT parameter    (name,new_name?,synopsis?,description?,datatype?,unit?,valid*,default?)>
<!ATTLIST parameter     action (auto|replace|drop) "auto"
                        is_numeric  (yes|no) "no"
                        occurrence  (once|multiple) "multiple">

<!ELEMENT result       (name,new_name?,synopsis?,description?,datatype?,unit?,default?)>
<!ATTLIST result        action (auto|replace|drop) "auto"
                        is_numeric  (yes|no) "no"
                        occurrence  (once|multiple) "multiple">

<!ELEMENT unit         (fraction|product|(base_unit,scaling?))>
<!ELEMENT fraction     (dividend,divisor)>
<!ELEMENT dividend     (fraction|product|(base_unit,scaling?))>
<!ELEMENT divisor      (fraction|product|(base_unit,scaling?))>
<!ELEMENT product      (factor+)>
<!ELEMENT factor       (fraction|product|(base_unit,scaling?))>

<!-- Valid 'datatype's are integer,float,string,text,date,timeofday,duration,timestamp,binary,boolean,version -->
<!ELEMENT datatype     (#PCDATA)>
<!ATTLIST datatype     size  (2|4|8)  "4">
<!-- Valid 'base_unit's are $ and % are none,%,byte,bit,flop,op,process,event,s,m,g,A,K,mol,cd,Y,$,EUR -->
<!ELEMENT base_unit    (#PCDATA)>
<!-- Valid 'scaling' factors are Kilo,Mega,Giga,Tera,Peta,milli,micro,nano,pico,femto,Ki,Mi,Gi,Ti,Pi -->
<!ELEMENT scaling      (#PCDATA)>

<!ELEMENT valid        (#PCDATA)>
<!ELEMENT default      (#PCDATA)>
<!ELEMENT experiment   (#PCDATA)>
<!ELEMENT name         (#PCDATA)>
<!ELEMENT new_name     (#PCDATA)>
<!ELEMENT organization (#PCDATA)>
<!ELEMENT project      (#PCDATA)>
<!ELEMENT host         (#PCDATA)>
<!ELEMENT port         (#PCDATA)>
<!ELEMENT user         (#PCDATA)>
<!ELEMENT group        (#PCDATA)>
<!ELEMENT passwd       (#PCDATA)>
<!ELEMENT synopsis     (#PCDATA)>
<!ELEMENT description  (#PCDATA)>
<!ELEMENT import       (#PCDATA)>
<!ELEMENT attachment   (#PCDATA)>

=== maxperf-de/perfbase/test/update/update_upd_4.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment_update SYSTEM "../../dtd/pb_experiment_update.dtd">

<!-- Rename a parameter -->
<experiment_update>
  <experiment>update_TEST</experiment>

  <info>
    <project>perfbase mega test suite</project>
  </info>

  <parameter>
    <name>machine</name>
    <new_name>platform</new_name>

    <default>SX-6</default>
  </parameter>

</experiment_update>

=== maxperf-de/perfbase/test/update/update_upd_1.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment_update SYSTEM "../../dtd/pb_experiment_update.dtd">

<!-- Add new parameter 'machine' -->
<experiment_update>
  <experiment>update_TEST</experiment>

  <info>
    <project>perfbase total testing</project>
  </info>

  <parameter occurrence="once">
    <name>machine</name>
    <synopsis>Machine type (SX, IA32/Myrinet, ...)</synopsis>

    <datatype>string</datatype>
    <unit>
      <base_unit>none</base_unit>
    </unit>
    <default>SX-5</default>
  </parameter>

  <parameter occurrence="once">
    <name>S_buf</name>
    <synopsis>size of intermediate buffer</synopsis>

    <datatype>integer</datatype>
    <unit>
      <base_unit>byte</base_unit>
    </unit>
  </parameter>

</experiment_update>

=== maxperf-de/perfbase/test/multi/multi_upd.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment_update SYSTEM "../../dtd/pb_experiment_update.dtd">

<experiment_update>
  <name>multi_TEST</name>

  <result>
    <name>CPU_load</name>
    <synopsis>Load of the CPU when processing this message transmission</synopsis>

    <datatype>float</datatype>
    <unit>
      <base_unit>%</base_unit>
    </unit>
  </result>

</experiment_update>

=== maxperf-de/perfbase/test/access/access_upd_5.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE experiment_update SYSTEM "../../dtd/pb_experiment_update.dtd">

<!-- Add a new parameter -->
<experiment_update>
  <name>access_TEST</name>

  <parameter occurrence="once">
    <name>interconnect</name>
    <synopsis>Type of interconect</synopsis>

    <datatype>string</datatype>
    <unit>
      <base_unit>none</base_unit>
    </unit>
    <default>IXS</default>
  </parameter>

</experiment_update>
